version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: |
          echo /etc/issue
          echo /etc/issue.net
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
